# Generated by Django 5.1.5 on 2025-01-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='dentist',
            new_name='doctor',
        ),
    ]
