# Generated by Django 5.1.4 on 2025-01-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_dentist_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
