# Generated by Django 5.1.4 on 2025-02-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
    ]
