# Generated by Django 5.1.4 on 2025-02-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
