# Generated by Django 5.1.4 on 2025-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionaloffer',
            name='description',
        ),
        migrations.AddField(
            model_name='promotionaloffer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionaloffer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionaloffer',
            name='title',
            field=models.CharField(default='Promotional Offer', max_length=200),
        ),
    ]
